import type { Metadata } from "next";
import "./globals.css";
import {Be_Vietnam_Pro} from "next/font/google";
import Header from "../components/layout/header";
const beVietnamPro = Be_Vietnam_Pro({ weight: ["400", "700"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
